artifact_uri: /Users/alainmorrisdev/development/KNUT/DRT/drt_research_platform/artifacts/mlflow/979759257152653683/4380bdb6b0af40eeabfd9e5348e0a665/artifacts
end_time: 1736071627450
entry_point_name: ''
experiment_id: '979759257152653683'
lifecycle_stage: active
run_id: 4380bdb6b0af40eeabfd9e5348e0a665
run_name: sweep_4
run_uuid: 4380bdb6b0af40eeabfd9e5348e0a665
source_name: ''
source_type: 4
source_version: ''
start_time: 1736071627443
status: 3
tags: []
user_id: alainmorrisdev
