name: fleet_optimization_test
description: "Study to optimize fleet size and vehicle capacity for DRT service"
version: "1.0.0"
authors:
  - "Research Team"
tags:
  - "fleet"
  - "optimization"
  - "capacity"

# MLflow configuration
mlflow:
  tracking_uri: "sqlite:///studies/mlflow.db"
  experiment_name: "DRT Fleet Optimization"
  artifact_location: "studies/artifacts"
  tags:
    study_type: "parameter_sweep"
    domain: "fleet_management"
    study_name: "fleet_optimization_test"
    version: "1.0.0"

# Execution settings
execution:
  distributed: false
  max_parallel: 4
  continue_on_error: true
  save_intermediate: true

# Simulation settings
simulation:
  start_time: "2024-10-24 07:00:00"
  end_time: "2024-10-24 23:00:00"
  warm_up_duration: 1800
  time_step: 30
  time_scale_factor: 1.0
  random_seed: 42

# Base configuration for all parameter sets
base_config:
  network:
    network_file: "data/networks/hwaseong_drive.graphml"
    walk_network_file: "data/networks/hwaseong_walk.graphml"
    coordinate_system: "EPSG:4326"
    walking_speed: 1.4
    driving_speed: 8.33
    service_area_polygon:
      - [126.827032, 37.198957]
      - [126.822082, 37.203549]
      - [126.818869, 37.206509]
      - [126.817734, 37.209793]
      - [126.832442, 37.216226]
      - [126.833297, 37.209711]
      - [126.836499, 37.210003]
      - [126.838809, 37.206861]
      - [126.844007, 37.201823]
      - [126.828538, 37.198760]
  
  demand:
    generator_type: "csv"
    num_requests: 20
    csv_config:
      files:
        - file_path: "data/demands/base_real_time.csv"
          weight: 1.0
      service_area_polygon:
        - [126.827032, 37.198957]
        - [126.822082, 37.203549]
        - [126.818869, 37.206509]
        - [126.817734, 37.209793]
        - [126.832442, 37.216226]
        - [126.833297, 37.209711]
        - [126.836499, 37.210003]
        - [126.838809, 37.206861]
        - [126.844007, 37.201823]
        - [126.828538, 37.198760]
      columns:
        request_time: "time"
        pickup_lat: "o_y"
        pickup_lon: "o_x"
        dropoff_lat: "d_y"
        dropoff_lon: "d_x"
  
  service:
    max_wait_time: 600
    max_ride_time: 1200
    max_walking_distance: 400.0
    max_journey_time: 1800
  
  algorithm:
    routing_algorithm: "time_dependent"
    cost_function: "multi_objective"
    user_acceptance_model: "logit"
    rebalancing_interval: 300
    stop_selector: "coverage_based"
    stop_selector_params:
      strategy: "coverage_based"
      max_walking_distance: 500
      min_stop_spacing: 200
      coverage_radius: 400
      min_demand_threshold: 2
      accessibility_weights:
        walk: 0.4
        demand: 0.3
        vehicle: 0.2
        coverage: 0.1
      custom_params:
        immediate_demand_window_minutes: 60
        historical_demand_window_hours: 12
        min_requests_for_cluster: 3
        cluster_weight: 0.7
        max_vehicle_distance: 1500
      candidate_stops_file: "data/candidate_stops/hwaseong.csv"
    stop_assigner: "multi_objective"
    stop_assigner_params:
      strategy: "multi_objective"
      max_alternatives: 3
      thresholds: {"max_walking_distance": 400.0, "max_walking_time": 300.0, "max_driving_time": 900.0}
      weights: {"vehicle_access_time": 0.3, "passenger_access_time": 0.7}

# Parameter sets to evaluate
parameter_sets:
  small_fleet:
    name: "small_fleet"
    description: "Small fleet configuration with varying capacities"
    replications: 1
    tags:
      - "small_fleet"
    vehicle:
      fleet_size: 10
      capacity: 4
      boarding_time: 5
      alighting_time: 5
      depot_locations:
        - [126.81736515, 37.209416]
        - [126.82221158, 37.20090886]
        - [126.83461236, 37.20602126]
        - [126.8299617, 37.20062122]
        - [126.83069764999999, 37.21154885]
    matching:
      assignment_method: "insertion"
      optimization_method: "none"
      assignment_config:
        constraints:
          max_waiting_time_secs: 300
          max_in_vehicle_time_secs: 900
          max_vehicle_access_time_secs: 600
          max_existing_passenger_delay_secs: 420
          max_distance_meters: 10000.0
        weights:
          passenger_waiting_time: 0.20
          passenger_in_vehicle_time: 0.40
          existing_passenger_delay: 0.30
          distance: 0.10
