artifact_uri: /Users/alainmorrisdev/development/KNUT/DRT/drt_research_platform/artifacts/mlflow/979759257152653683/4628c1505d0d4319b5f2a3efd49e3efe/artifacts
end_time: 1736070809147
entry_point_name: ''
experiment_id: '979759257152653683'
lifecycle_stage: active
run_id: 4628c1505d0d4319b5f2a3efd49e3efe
run_name: fleet_demand_study
run_uuid: 4628c1505d0d4319b5f2a3efd49e3efe
source_name: ''
source_type: 4
source_version: ''
start_time: 1736070809142
status: 3
tags: []
user_id: alainmorrisdev
