# drt_sim/config/defaults/default_scenario.yaml
name: "default_scenario"
description: "Default DRT simulation scenario"

simulation:
  start_time: "2024-01-01T06:00:00"
  end_time: "2024-01-01T22:00:00"
  time_step: 60  # seconds
  warm_up_period: 60  # minutes
  cool_down_period: 60  # minutes
  random_seed: 42

vehicle:
  fleet_size: 10
  vehicle_capacity: 4
  vehicle_speed: 30  # km/h
  boarding_time: 30  # seconds
  alighting_time: 30  # seconds
  depot_locations:
    - [52.5200, 13.4050]  # Example coordinates

demand:
  demand_level: 60  # requests per hour
  spatial_distribution: "uniform"
  temporal_distribution: "poisson"
  max_wait_time: 20  # minutes
  max_detour_ratio: 0.3
  cancellation_probability: 0.1
  prebooking_ratio: 0.2
  demand_patterns:
    morning_peak: 1.5
    evening_peak: 1.3
    off_peak: 0.7

stop:
  max_walking_distance: 300  # meters
  min_stop_spacing: 200  # meters
  stop_capacity: 10
  safety_threshold: 0.8
  accessibility_weight: 0.7
  coverage_radius: 500  # meters

algorithm:
  routing_algorithm: "dijkstra"
  dispatch_algorithm: "batch_dispatch"
  matching_algorithm: "hungarian_matching"
  matching_policy: "balanced_load"
  reoptimization_interval: 300  # seconds
  max_computation_time: 10  # seconds
  batch_interval: 30  # seconds
  batch_size: 10
  max_matches_per_vehicle: 3
  max_waiting_requests: 100
  min_pickup_delay: 300  # seconds
  max_pickup_delay: 1800  # seconds
  
  # Granular cost weights for each component
  stop_selection_costs:
    walking_distance: 0.3
    coverage: 0.2
    accessibility: 0.15
    safety: 0.15
    demand_density: 0.1
    transfer_potential: 0.05
    infrastructure: 0.05

  matching_costs:
    wait_time: 0.3
    detour_time: 0.25
    vehicle_capacity: 0.15
    ride_time: 0.15
    passenger_preference: 0.1
    vehicle_suitability: 0.05

  dispatch_costs:
    idle_time: 0.25
    deadhead_distance: 0.2
    fleet_distribution: 0.15
    energy_consumption: 0.15
    vehicle_load: 0.15
    time_to_pickup: 0.1

  routing_costs:
    distance: 0.3
    travel_time: 0.25
    reliability: 0.15
    road_type: 0.1
    traffic_conditions: 0.1
    turns_complexity: 0.05
    elevation: 0.05

  rebalancing_costs:
    demand_prediction: 0.3
    current_coverage: 0.25
    distance_to_hotspot: 0.2
    time_of_day: 0.15
    historical_patterns: 0.1

network_file: "networks/default_network.osm"
output_directory: "output/default_scenario"