metadata:
  name: "fleet_size_optimization"
  description: "Optimize fleet size for different demand patterns and service areas"
  version: "1.0.0"
  tags: ["fleet-optimization", "efficiency", "capacity-planning"]
  authors: ["Research Team"]
  created_at: "2025-01-05T16:00:00"

type: "parameter_sweep"

parameter_sweep:
  enabled: true
  method: "grid"
  parameters:
    vehicle.fleet_size: [5, 10, 15, 20, 25, 30]
    vehicle.capacity: [4, 6, 8]
    algorithm.cost_function_params.weights.waiting_time: [0.3, 0.4, 0.5]

base_config:
  vehicle:
    speed: 10.0        # meters per second
    boarding_time: 5  # seconds
    alighting_time: 5
    depot_locations:
      - [37.5666, 127.0000]
      - [37.5778, 126.9982]
      - [37.5550, 127.0011]
  algorithm:
    dispatch_strategy: "fcfs"
    matching_algorithm: "batch"
    routing_algorithm: "dijkstra"
    cost_function: "simple"
    batch_interval: 30
    optimization_horizon: 1800
  network:
    network_file: "data/networks/hwaseong_drive.graphml"
    walk_network_file: "data/networks/hwaseong_walk.graphml"
    coordinate_system: "EPSG:4326"
    walking_speed: 1.4

metrics:
  collect_interval: 300
  save_interval: 1800
  default_metrics:
    - waiting_time
    - in_vehicle_time
    - total_distance
    - occupancy_rate
    - service_rate
    - rejection_rate
  additional_metrics:
    - fleet_efficiency
    - passenger_per_vehicle_hour
    - deadhead_ratio
    - vehicle_utilization
    - operational_cost

simulation:
  start_time: "2025-01-01 07:00:00"
  end_time: "2025-01-01 19:00:00"
  warm_up_duration: 1800
  time_step: 60
  time_scale_factor: 1.0
  replications: 5