artifact_uri: /Users/alainmorrisdev/development/KNUT/DRT/drt_research_platform/artifacts/mlflow/979759257152653683/eadf855e1bfa45bab27f48f23ed2f4ff/artifacts
end_time: 1736071627452
entry_point_name: ''
experiment_id: '979759257152653683'
lifecycle_stage: active
run_id: eadf855e1bfa45bab27f48f23ed2f4ff
run_name: fleet_demand_study
run_uuid: eadf855e1bfa45bab27f48f23ed2f4ff
source_name: ''
source_type: 4
source_version: ''
start_time: 1736071627407
status: 3
tags: []
user_id: alainmorrisdev
