artifact_location: /Users/alainmorrisdev/development/KNUT/DRT/drt_research_platform/artifacts/mlflow/979759257152653683
creation_time: 1736070464724
experiment_id: '979759257152653683'
last_update_time: 1736070464724
lifecycle_stage: active
name: fleet_demand_study
