artifact_uri: /Users/alainmorrisdev/development/KNUT/DRT/drt_research_platform/artifacts/mlflow/979759257152653683/d1bee8a01cd34818a98e88ac5f9cea98/artifacts
end_time: 1736070921658
entry_point_name: ''
experiment_id: '979759257152653683'
lifecycle_stage: active
run_id: d1bee8a01cd34818a98e88ac5f9cea98
run_name: shivering-ram-178
run_uuid: d1bee8a01cd34818a98e88ac5f9cea98
source_name: ''
source_type: 4
source_version: ''
start_time: 1736070921639
status: 3
tags: []
user_id: alainmorrisdev
