artifact_uri: /Users/alainmorrisdev/development/KNUT/DRT/drt_research_platform/artifacts/mlflow/979759257152653683/4f5ce8e7c392408b858aac552cf4cdae/artifacts
end_time: 1736070809141
entry_point_name: ''
experiment_id: '979759257152653683'
lifecycle_stage: active
run_id: 4f5ce8e7c392408b858aac552cf4cdae
run_name: loud-goat-979
run_uuid: 4f5ce8e7c392408b858aac552cf4cdae
source_name: ''
source_type: 4
source_version: ''
start_time: 1736070809122
status: 3
tags: []
user_id: alainmorrisdev
