artifact_uri: /Users/alainmorrisdev/development/KNUT/DRT/drt_research_platform/artifacts/mlflow/979759257152653683/5cd8b6a0bbba4bdab1c6cb365bcabeac/artifacts
end_time: 1736071627427
entry_point_name: ''
experiment_id: '979759257152653683'
lifecycle_stage: active
run_id: 5cd8b6a0bbba4bdab1c6cb365bcabeac
run_name: sweep_1
run_uuid: 5cd8b6a0bbba4bdab1c6cb365bcabeac
source_name: ''
source_type: 4
source_version: ''
start_time: 1736071627420
status: 3
tags: []
user_id: alainmorrisdev
