artifact_location: /Users/alainmorrisdev/development/KNUT/DRT/drt_research_platform/artifacts/mlflow/0
creation_time: 1736070464720
experiment_id: '0'
last_update_time: 1736070464720
lifecycle_stage: active
name: Default
