artifact_uri: /Users/alainmorrisdev/development/KNUT/DRT/drt_research_platform/artifacts/mlflow/979759257152653683/1afe4d04c7d949c4bc8ce9005698cd97/artifacts
end_time: 1736070921701
entry_point_name: ''
experiment_id: '979759257152653683'
lifecycle_stage: active
run_id: 1afe4d04c7d949c4bc8ce9005698cd97
run_name: fleet_demand_study
run_uuid: 1afe4d04c7d949c4bc8ce9005698cd97
source_name: ''
source_type: 4
source_version: ''
start_time: 1736070921659
status: 3
tags: []
user_id: alainmorrisdev
