artifact_uri: /Users/alainmorrisdev/development/KNUT/DRT/drt_research_platform/artifacts/mlflow/979759257152653683/fbc2cd30aa8744ab8335baa0ffa779b5/artifacts
end_time: 1736070726644
entry_point_name: ''
experiment_id: '979759257152653683'
lifecycle_stage: active
run_id: fbc2cd30aa8744ab8335baa0ffa779b5
run_name: clean-bass-53
run_uuid: fbc2cd30aa8744ab8335baa0ffa779b5
source_name: ''
source_type: 4
source_version: ''
start_time: 1736070726626
status: 3
tags: []
user_id: alainmorrisdev
