artifact_uri: /Users/alainmorrisdev/development/KNUT/DRT/drt_research_platform/artifacts/mlflow/979759257152653683/6f4bcb9f10be4b85b5c2c3e7a2753eb9/artifacts
end_time: 1736070557422
entry_point_name: ''
experiment_id: '979759257152653683'
lifecycle_stage: active
run_id: 6f4bcb9f10be4b85b5c2c3e7a2753eb9
run_name: adaptable-dove-315
run_uuid: 6f4bcb9f10be4b85b5c2c3e7a2753eb9
source_name: ''
source_type: 4
source_version: ''
start_time: 1736070557389
status: 3
tags: []
user_id: alainmorrisdev
